# Great reference:  http://www.appveyor.com/docs/appveyor-yml

version: 1.0.{build}
skip_tags: false
configuration: Release
cache:
- packages -> **\packages.config
init:
<<<<<<< HEAD
- ps: .\BuildScripts\init.ps1
=======
- ps: >-
    $parsedReleaseBuildVersion = $env:APPVEYOR_REPO_TAG_NAME -Match "(\d+.\d+.\d+(.\d+)?)"
    
    If($env:appveyor_repo_tag -AND $parsedReleaseBuildVersion) {
      $env:BuildVersion = $matches[0]
      $env:IsGithubRelease = $TRUE
    }
    else {
      $env:BuildVersion = $env:appveyor_build_version
      $env:IsGithubRelease = ""
    }
    
    Write-Host "Build Version: " $env:BuildVersion
    
    Write-Host "appveyor_build_version Variable: " $env:appveyor_build_version
>>>>>>> 8d8cedd183dd815e4e68f8b271af1c00eeb66e2a
install:
- ps: .\BuildScripts\install.ps1
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(BuildVersion)
  assembly_file_version: $(BuildVersion)
  assembly_informational_version: $(BuildVersion)
nuget:
  account_feed: true
  project_feed: true
before_build:
- nuget restore CloudWatchAppender\CloudWatchAppender.sln -verbosity detailed
after_build:
- ps: .\BuildScripts\after_build.ps1
build:
  project: CloudWatchAppender\CloudWatchAppender.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
artifacts:
<<<<<<< HEAD
- path: CloudWatchAppender.$(BuildVersion).nupkg
=======
- path: /.*\.nupkg/
>>>>>>> 8d8cedd183dd815e4e68f8b271af1c00eeb66e2a
  name: CloudWatchAppender
deploy:
- provider: GitHub
  auth_token:
    secure: ioxuMU09l+pPETzGYBz4oElm1jw68rlSf81AU5KcDc4VAzsgYfB/iqvGhPlHfxoe
  artifact: 
  prerelease: false
  on:
    branch: master
    IsGithubRelease: true
- provider: NuGet
  api_key:
    secure: xrh/cFtPH7iBByeeTRQqRbnf88YMmCsZIjdzut9dW4sJrfhWt6lphG7KcqpDwrleAT82B9b6w86XS6j78Csmjvl0mz41xJ374ncCs3vnsxA=
  artifact: /.*\.nupkg/
  on:
    branch: master
    IsGithubRelease: true
