# Great reference:  http://www.appveyor.com/docs/appveyor-yml

version: 1.0.{build}
skip_tags: false
configuration: Release
cache:
- packages -> **\packages.config
install:
  - ps: .\BuildScripts\install.ps1
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(BuildVersion)
  assembly_file_version: $(BuildVersion)
  assembly_informational_version: $(BuildVersion)
nuget:
  account_feed: true
  project_feed: true
before_build:
- nuget restore CloudWatchAppender\CloudWatchAppender.sln -verbosity detailed
after_build:
  - ps: .\BuildScripts\after_build.ps1
build:
  project: CloudWatchAppender\CloudWatchAppender.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
artifacts:
- path: CloudWatchAppender.$(BuildVersion).nupkg
  name: CloudWatchAppender
deploy:
- provider: GitHub
  auth_token:
    secure: ioxuMU09l+pPETzGYBz4oElm1jw68rlSf81AU5KcDc4VAzsgYfB/iqvGhPlHfxoe
  artifact: 
  prerelease: false
  on:
    branch: CloudWatchAppenderv4
    IsGithubRelease: true
- provider: NuGet
  api_key:
    secure: nJSdlo2bRHEauK9vfPjJvhao5uLnsuaDIdebgN6kmNVW0jGQBxwxhTUJPg0/nxwg
  artifact: /.*\.nupkg/
  on:
    branch: CloudWatchAppenderv4
    IsGithubRelease: true
