# Great reference:  http://www.appveyor.com/docs/appveyor-yml

version: 1.0.{build}
skip_tags: false
configuration: Release
init:
- ps: >-
    $parsedReleaseBuildVersion = $env:APPVEYOR_REPO_TAG_NAME -Match "(\d+.\d+.\d+(.\d+)?)"
    
    If($env:appveyor_repo_tag -AND $parsedReleaseBuildVersion) {
      $env:BuildVersion = $matches[0]
      $env:IsGithubRelease = $TRUE
    }
    else {
      $env:BuildVersion = $env:appveyor_build_version
      $env:IsGithubRelease = ""
    }
    
    Write-Host "Build Version: " $env:BuildVersion
    
    Write-Host "appveyor_build_version Variable: " $env:appveyor_build_version
	
install:
- ps: >-
    try
    {
        if($env:IsGithubRelease)
        {
            $origin = git config --get remote.origin.url
            if ($origin -like "https://github.com/*.git")
            {
                $startToTrim = "https://github.com/"
                $endToTrim = ".git"

                $releaseUrl = $origin.Substring($startToTrim.Length, $origin.Length - $startToTrim.Length - $endToTrim.Length)
                
                $releaseUrl = "https://api.github.com/repos/" + $releaseUrl + "/releases/tags/" + $env:APPVEYOR_REPO_TAG_NAME

                $resp = invoke-webrequest $releaseUrl
                $release = $resp.Content | ConvertFrom-Json

                $nuspecPath = (Get-ChildItem -Filter *.nuspec -Recurse )[0].FullName
                [xml]$nuspec = Get-Content $nuspecPath

                $nuspec.package.metadata.releaseNotes = $release.Body
                $nuspec.package.metadata.version = $(BuildVersion)
                $nuspec.Save( $nuspecPath )
            }
        }
    }
    catch 
    {
        Write-Host $_.Exception.GetType().FullName, $_.Exception.Message
    }
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(BuildVersion)
  assembly_file_version: $(BuildVersion)
  assembly_informational_version: $(BuildVersion)
nuget:
  account_feed: true
  project_feed: true
before_build:
- nuget restore CloudWatchAppender\CloudWatchAppender.sln
after_build:
- ps: >-
    try
    {
      #Create Folder Structure
      New-Item -Force -ItemType directory -Path build\lib\net35
      New-Item -Force -ItemType directory -Path build\lib\net45

      #Copy Files into folders
      Copy-Item -Force "CloudWatchAppender3.5\bin\Release\CloudWatchAppender.dll" "build\lib\net35"
      Copy-Item -Force "CloudWatchAppender3.5\bin\Release\CloudWatchAppender.pdb" "build\lib\net35"
      Copy-Item -Force "CloudWatchAppender\bin\Release\CloudWatchAppender.pdb" "build\lib\net45"
      Copy-Item -Force "CloudWatchAppender\bin\Release\CloudWatchAppender.pdb" "build\lib\net45"
      $nuspecPath = (Get-ChildItem -Filter *.nuspec -Recurse )[0].FullName
      nuget pack $nuspecPath
    }
    catch 
    {
        Write-Host $_.Exception.GetType().FullName, $_.Exception.Message
    }
build:
  project: CloudWatchAppender\CloudWatchAppender.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
artifacts:
- path: 
  name: CloudWatchAppender
deploy:
- provider: GitHub
  auth_token:
    secure: ioxuMU09l+pPETzGYBz4oElm1jw68rlSf81AU5KcDc4VAzsgYfB/iqvGhPlHfxoe
  artifact: 
  prerelease: false
  on:
    branch: master
    IsGithubRelease: true
- provider: NuGet
  api_key:
    secure: xrh/cFtPH7iBByeeTRQqRbnf88YMmCsZIjdzut9dW4sJrfhWt6lphG7KcqpDwrleAT82B9b6w86XS6j78Csmjvl0mz41xJ374ncCs3vnsxA=
  artifact: /.*\.nupkg/
  on:
    branch: master
    IsGithubRelease: true
